image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  #Application
  APPLICATION_NAME: bys-msa
  APP_NAME: board
  APPLICATION_NS: smp
  APPLICATION_PORT: 8090
  
  # AWS 
  AWS_REGION: "ap-northeast-2"
  REGISTRY_URL: 718652001716.dkr.ecr.ap-northeast-2.amazonaws.com
 
stages:
  - build
  - package
  - deploy
  - deploycheck
  - rollback

maven-build:
  image: maven:3.8.1-openjdk-11
  stage: build
  script:
    
    # Build
    - mvn package

  artifacts:
    when: always
    paths:
      - target/
    expire_in: 1 days

  only:
    - develop
    - stage
    - master


docker-build:
  stage: package
  script:

    # Change Variables <APPLICATION_NS>-<APP_NAME>
    - sed -i "s/<APPLICATION_NS>/${APPLICATION_NS}/g" env/${ENVIRONMENT}/Dockerfile
    - sed -i "s/<APP_NAME>/${APP_NAME}/g" env/${ENVIRONMENT}/Dockerfile
    - sed -i "s/<APPLICATION_PORT>/${APPLICATION_PORT}/g" env/${ENVIRONMENT}/Dockerfile
    - sed -i "s/<ENVIRONMENT>/${ENVIRONMENT}/g" env/${ENVIRONMENT}/Dockerfile

    - sed -i "s/<JENNIFER_MANAGER_IP>/${JENNIFER_MANAGER_IP}/g" env/${ENVIRONMENT}/Dockerfile
    - sed -i "s/<JENNIFER_MANAGER_PORT>/${JENNIFER_MANAGER_PORT}/g" env/${ENVIRONMENT}/Dockerfile
    - sed -i "s/<JENNIFER_DOMAIN_ID>/${JENNIFER_DOMAIN_ID}/g" env/${ENVIRONMENT}/Dockerfile
    
    - sed -i "s/<APPLICATION_NS>/${APPLICATION_NS}/g" env/${ENVIRONMENT}/server.xml
    - sed -i "s/<APP_NAME>/${APP_NAME}/g" env/${ENVIRONMENT}/server.xml
    - sed -i "s/<APPLICATION_PORT>/${APPLICATION_PORT}/g" env/${ENVIRONMENT}/server.xml
    
    
    ### Docker Build
    - docker build -t ${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA} .

    ### Check Latest Image
    - export IS_LATEST=`aws ecr describe-images --region ${AWS_REGION} --repository-name ${ENVIRONMENT}-${APPLICATION_NAME} --query imageDetails[].imageTags | grep ${APP_NAME}-latest | wc -l`
    ### Docker Backup
    - >
     if [ "$IS_LATEST" == "1" ]; then
       echo "Image Backup";
       docker pull ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-latest;
       docker tag ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-latest ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-backup;
       docker push ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-backup;
       docker rmi ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-latest;
     fi
    
    ### Docker Push into ECR
    - docker tag ${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA} ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA}
    - docker push ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA}

    - docker tag ${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA} ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-latest
    - docker push ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-latest

    ### Docker Delete Images
    - docker rmi ${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA}
    - docker rmi ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${CI_COMMIT_SHORT_SHA}
    - docker rmi ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-latest
    - docker rmi ${REGISTRY_URL}/${ENVIRONMENT}-${APPLICATION_NAME}:${APP_NAME}-backup

  only:
    - develop
    - stage
    - master

  

# Deploy
deploy:
  stage: deploy
  image: ${REGISTRY_URL}/common/helm-deploy:latest
  script:
    
    - helm upgrade -i --debug ${APP_NAME}-${ENVIRONMENT} ./helm/ -f ./helm/${HELM_VALUES_FILE}
     -n ${APPLICATION_NS}
     
  only:
    - develop
    - stage
    - master

# Deploy-Check 
deploycheck:
  stage: deploycheck
  image: ${REGISTRY_URL}/common/helm-deploy:latest
  script:
    
    # Check Status
    - kubectl rollout status deployment ${APP_NAME}-${ENVIRONMENT}-deploy -n ${APPLICATION_NS}

  only:
    - develop
    - stage
    - master


# Deploy-Check 
rollback:
  stage: deploycheck
  when: manual
  image: ${REGISTRY_URL}/common/helm-deploy:latest
  script:
    
    ## Deploy Backup
    - helm upgrade -i --debug --set image.tag=${APP_NAME}-backup ${APP_NAME}-${ENVIRONMENT} ./helm/ -f ./helm/${HELM_VALUES_FILE}
     -n ${APPLICATION_NS}
  
  only:
    - develop
    - stage
    - master