############ Common ############

############ Deployment.yaml ############
deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

replicaCount: 1

imagePullSecrets: []

volumes:
  - name: ba-scp-volume
    hostPath:
      path: /fsutil/scp/ba_scp
      type: Directory

volumeMounts:
  - mountPath: /fsutil/scp/ba_scp
    name: ba-scp-volume

image:
  repository: "<REGISTRY_URL>/<ENVIRONMENT>-<APPLICATION_NAME>"
  tag: "<CI_COMMIT_SHORT_SHA>"
  pullPolicy: Always

containerPort: <APPLICATION_PORT>

resources:
  requests:
    cpu: 800m
    memory: 1536Mi
  limits:
    cpu: 1600m
    memory: 1536Mi

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-group-type
                  operator: In
                  values:
                  - <APPLICATION_GROUP>
        podAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 99
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - <APPLICATION_NAME>-<ENVIRONMENT>
                topologyKey: "kubernetes.io/hostname"
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: "app.kubernetes.io/name"
                    operator: In
                    values:
                    - <APPLICATION_NAME>-<ENVIRONMENT>
                topologyKey: "failure-domain.beta.kubernetes.io/zone"


############ service.yaml ############
service:
  type: ClusterIP
  port: <APPLICATION_PORT>


############ ingress.yaml ############
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: <APPLICATION_GROUP>-<ENVIRONMENT>
    alb.ingress.kubernetes.io/subnets: SEOUL-MyData-DEV-A-WEB-DHCP-SBN, SEOUL-MyData-DEV-C-WEB-DHCP-SBN
    alb.ingress.kubernetes.io/scheme : internal
    alb.ingress.kubernetes.io/security-groups: SEOUL-MyData-DEV-EKSALB-OPENBANKING-SG
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /<APPLICATION_NAME>/
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '10'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '4'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/target-type: ip
  rules:
    - http:
        paths:
        - path: /<APPLICATION_NAME>
          pathType: Prefix
          backend:
            service:
              name: <APPLICATION_NAME>-<ENVIRONMENT>-service
              port:
                number: <APPLICATION_PORT>
  tls: []
  

############ hpa.yaml ############
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

############ serviceaccount.yaml ############
serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
